### ISSUE TITLE
Publication and code 

### ISSUE THREAD

**Issue by nezix** [wlincong/SESexact#1]
Hello,

Do you have a publication for this tool?
Also there is no source code in the repository, do you plan to distribute it?

**Comment by wlincong** [comment]
Hello,
     First of all, thank you for your interests in sesExact. The manuscript for sesExact is under preparation and hopefully will be published soon. No, at this moment I do not have plan to distribute my source code. Even though the codes for SES computation and triangulation are very close to be final, the codes for GUI and visualization per se remain to be preliminary, and the codes for using sesExact-generated SESs to analyze ligand-protein interface etc have not been written.  BTW, I just update both the linux and windows version to v002.  Please take a look at them. Thanks.

**Comment by wlincong** [comment]
HI,
   I have uploaded a program, sesA, for the computations of both solvent-accessible surface area and solvent-excluded surface area. It is a sister program of my sesX that focuses on SES computation/triangulation. I believe sesA is much more accurate and much more robust than Sanner's MSMS program.  If you are interested in it, please let me know. Thanks. Lincong
